dependencies:
  - name: nodejs
    version: ~1.9.0
    repository: '@hmctspublic'
  - name: redis
    version: ~10.0.0
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: idam-pr
    version: ~2.2.5
    repository: '@hmctspublic'
    condition: idam-pr.enabled
