nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
     NODE_TLS_REJECT_UNAUTHORIZED: 0
     SERVICES_IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
     SERVICES_IDAM_LOGIN_URL: https://idam-web-public.aat.platform.hmcts.net
     REDISCLOUD_URL: redis://ignore:fake-password@${SERVICE_NAME}-redis-master:6379
     LAUNCH_DARKLY_CLIENT_ID: 5de6610b23ce5408280f2268
     DEBUG: xuiNode:*
  keyVaults:
    rpx:
      secrets:
        - mc-s2s-client-secret
        - mc-idam-client-secret
        - mc-pact-ca-bundle-cert
        - pp-test
redis:
  enabled: true

